### ISSUE TITLE
Visually inform user when we're creating a cluster

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#103]
When pressing the new cluster button there is currently no feedback to the user that we're doing something.  This is fine if the cluster comes up quickly (as is the case for LocalCluster) but quite stressful when the cluster takes a while (such as is the case when the Scheduler must be run on a remote machine).  In this case the user has the stress of figuring out if they actually pressed the button or not.  If so, they need to wait and not press it again (or else they'll create many clusters).

**Comment by ian-r-rose** [comment]
Yeah, good point. We can disable the button and try to put a spinner somewhere while the cluster is creating.

**Comment by jsignell** [comment]
I think a disabled button with a spinner on it is a decent solution as long as it is fairly good at re-enabling itself. I am trying to remind myself how jlab works and taking a look at this now.

**Comment by ian-r-rose** [comment]
Thanks for taking a crack at this @jsignell! Let me know if you need any orientation around the code base.
