### ISSUE TITLE
Individual plot buttons not appearing

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-labextension#107]
IIUC the plots specified in `individual-plots.json` (like the new [cluster map](https://github.com/dask/distributed/pull/3361)) should show up as buttons in the lab extension. I followed the installation instructions in the README:

```
conda install jupyterlab nodejs
pip install dask_labextension
jupyter labextension install dask-labextension
```

But am not getting a button for the cluster map plot (or any of the individual plots)

<img width="1440" alt="Screen Shot 2020-01-17 at 9 35 29 AM" src="https://user-images.githubusercontent.com/11656932/72624918-5ca69300-390d-11ea-832a-064af2d5077b.png">

Am I missing an installation step, or perhaps something else?

**Comment by mrocklin** [comment]
This discovery currently only works if you create the cluster from the
JupyterLab widget itself unfortunately.

**Comment by jrbourbeau** [comment]
Hrm, I still don't get the individual plots when creating the cluster via the lab widget (i.e. pressing the "+ New") button

**Comment by ian-r-rose** [comment]
What versions of of the python package and labextension do you have installed?

Do things start working if you reset your JupyterLab? (go to `/lab?reset`)

**Comment by jrbourbeau** [comment]
I'm using `1.1.0` of the python `dask-labextension` package and `v0.3.0` of the labextension (gotten from the output of `jupyter labextension list`). After going to `/lab?reset`, things did reset, but no buttons from the individual plots appeared

**Comment by ian-r-rose** [comment]
That version of the lab extension is fairly old, I'm not sure why that would have been installed into your application (perhaps you are also using an older JLab?).

Can you try installing the most recent version (v1.1.0)?

```
jupyter labextension install dask-labextension@1.1.0
```

**Comment by ian-r-rose** [comment]
I should note that we currently don't have a very good way to ensure that the server-side and client-side components to this are compatible with each other, unfortunately. We should probably make a compatibility table in the README here.

**Comment by jrbourbeau** [comment]
Woo, that worked! 

I was able to install 1.1.0 after upgrading my jupyterlab to the latest release. Now things are working great! Thanks @ian-r-rose @mrocklin

**Comment by ian-r-rose** [comment]
Great!
