### ISSUE TITLE
Support for HTTPS connections

### ISSUE THREAD

**Issue by sntgluca** [dask/dask-labextension#108]
Dear all,

I have a system running Jupyter servers behind a nginx proxy, for which the calls has to be served via https.
In this environment I get the following error:

```
Mixed Content: The page at 'https:<ADDRESS>' was loaded over HTTPS,
but requested an insecure resource 'http://<ADDRESS>/individual-task-stream'.
This request has been blocked; the content must be served over HTTPS.
```
Is there any configuration recommendation to enforce the use of https over http, or could it be implemented?

Alternatively may someone point to a configuration change which would allow loading the mixed content (even if it's arguably not the cleanest idea...)

Thanks!

**Comment by jacobtomlinson** [comment]
In your example here is `<ADDRESS>` the same address?

Serving mixed content is not possible for security reasons. Allowing http content within an https session will open you up to MITM attacks.

The solution for this is to server the Dask dashboard from an https endpoint. Could you provide more information about how you are starting your Dask cluster? Are you using the extension or creating it from within your notebook session?

**Comment by sntgluca** [comment]
Dear @jacobtomlinson ,
thanks for helping out. 

The proxy server and JupyterHub are on the same machine. This is the `ADDRESS` URL I mentioned above.

JupyterHub starts a jupyter server on a HPC cluster using `batchspawner` and its address changes all the time. Let me call it `NODE ADDRESS` in the following.
 
I then start dask with `SGEcluster` from `dask_jobqueue` to spawn workers on the same UGE cluster.

As you said, I'd be happy to start the dask dashboard via https, but I don't know how to do it.
Here's an example:

```python
import dask_jobqueue

cluster = dask_jobqueue.SGECluster(walltime="3600",
                                   resource_spec='m_mem_free=2G',
                                   memory='2G',
                                   processes=1, cores=1)
```

This creates a dask dashboard at `http://NODE ADDRESS:8087`.

Incidentally, I have a similar problem with `jupyterlab-nvdashboard`, which tries to connect to the bokeh server via `ws` while I need `wss`, and I don't know how to enforce the encryption.

I am not sure if I should change my JupyterHub configuration. if I can change anything on the JupyterHub config to force using SSL, I'd love to, but I wasn't able to find the right set of parameters.

Any help would be appreciated.

**Comment by jacobtomlinson** [comment]
@sntgluca apologies for the delay!

It sounds like a reasonable approach. As the Dask scheduler is running within the Jupyter kernel you should be able to access the dashboard via https using the Jupyter server proxy. For example your dashboard should be available at something like `https://ADDRESS/<username>/proxy/8087`.

Could you confirm that this is possible and also share the value of `cluster.dashboard_link`?

**Comment by sntgluca** [comment]
Hi @jacobtomlinson,

thanks for getting back to me, I should have jumped on this ticket earlier again as well.

Your suggestions made me think, and I can indeed confirm that I can start encrypted connections to both a dask dashboard and a bokeh server **by connecting to the JupyterHub proxy via `https`** from the browser.

I was somehow assuming that the browser would not play a role, and the connections would only depend on the proxy/Jupyterhub configuration and setup.

So for future references - for anyone at my level of understanding: if things don't work, make sure you explicitly use the encrypted `https` connection from your browser...

**Comment by jacobtomlinson** [comment]
Thanks for getting back to me. For further clarity could you confirm that this is now working for you in the dask lab extension? Does it correctly detect the https url or do you need ot manually change it? If not you may need to set the diagnostics link template string in your configuration.

**Comment by sntgluca** [comment]
Sorry that I wasn't clear. I can confirm I didn't need any manual change.

Accessing my service at `https://<PROXY_ADDRESS>` _from the browser_ propagates the protocol correctly down to the dask `https` url.

Best,
Gianluca

**Comment by jacobtomlinson** [comment]
Ah sure makes sense. Thanks!
