### ISSUE TITLE
Lab log "flooded" with UserWarnings about WorkerState.nthreads

### ISSUE THREAD

**Issue by michaelaye** [dask/dask-labextension#112]
I'm trying out dask-labextension on macOS 10.14.6 using Safari 13.0.4.

After launching a LocalCluster using the GUI of the labextension: "+ NEW" the cluster is started (8 cores, 4 workers), and everytime I do something in jupyterlab, like going back to the Safari tab with Jupyterlab or change to a different notebook I get this warning:

> /Users/klay6683/miniconda3/envs/py37/lib/python3.7/site-packages/distributed/scheduler.py:323: UserWarning: WorkerState.ncores has moved to WorkerState.nthreads

It's not a very fast "flooding" (hence the quotes), but it seems to be un-ended.

More version info:
dask 2.10.1
dask-core 2.10.1
dask_labexension 0.3.3
distributed 2.10.0
jupyterlab 1.2.6

**Comment by jacobtomlinson** [comment]
> I get this warning

Where are you seeing this warning?

**Comment by michaelaye** [comment]
The jupyterlab log. (“Lab log” in the title)

**Comment by jacobtomlinson** [comment]
Could you try a more recent version of the lab extension? `0.3.3` is a little dated now, `1.1.0` is the latest.

**Comment by michaelaye** [comment]
Oh I see.  Sure, I got this via conda-forge just two days ago. Will try pip then.

**Comment by jacobtomlinson** [comment]
That is curious as conda forge is up to date. https://anaconda.org/conda-forge/dask-labextension/files

**Comment by michaelaye** [comment]
```bash
$ conda list dask                                                                      (py37)
# packages in environment at /Users/klay6683/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
dask                      2.10.1                     py_0    conda-forge
dask-core                 2.10.1                     py_0    conda-forge
dask_labextension         0.3.3                      py_0    conda-forge
klay6683@macl3886|~/D/d/d/l1a_data
$ conda update --all                                                                   (py37)
Collecting package metadata (current_repodata.json): done
Solving environment: - ^[done

# All requested packages already installed.

klay6683@macl3886|~/D/d/d/l1a_data
$ conda update dask_labextension                                                       (py37)
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
I guess something in my large environment's dependency declaration is blocking that update.
It's here if you want to scan for potential culprits:
https://gist.github.com/5454ddc10c24f653a787c841269b6c4c

**Comment by michaelaye** [comment]
it's a pity that conda's reverse-dependency search still doesn't work (IIUC).

**Comment by michaelaye** [comment]
I "brutally" updated with pip and can confirm that this issue goes away.

Side note: Can I infer from what pip installed, that the dependency issue must be with one of these packages?

```
Successfully installed aiohttp-3.6.2 async-timeout-3.0.1 dask-labextension-1.1.0 jupyter-server-proxy-1.2.0 multidict-4.7.4 simpervisor-0.3
```
