### ISSUE TITLE
Update to use Bokeh >=2

### ISSUE THREAD

**Issue by andersy005** [dask/dask-labextension#121]
It appears that the most recent release of bokeh(v2.0.0) included some breaking changes. As a result, the websocket connection is not being established properly:

<img width="844" alt="Screen Shot 2020-03-19 at 1 55 28 PM" src="https://user-images.githubusercontent.com/13301940/77109358-5f933200-69e9-11ea-96ef-bcb2a2ab8197.png">
<img width="768" alt="Screen Shot 2020-03-19 at 1 54 51 PM" src="https://user-images.githubusercontent.com/13301940/77109363-61f58c00-69e9-11ea-98b6-e9963b111712.png">

I am running:

```
# Name                    Version                   Build  Channel
dask                      2.12.0                     py_0    conda-forge
dask-core                 2.12.0                     py_0    conda-forge
dask-labextension         2.0.0                      py_0    conda-forge
bokeh                     2.0.0            py37hc8dfbb8_0    conda-forge
```

```
$ jupyter labextension list
JupyterLab v2.0.1
Known labextensions:
   app dir: /glade/work/abanihi/softwares/miniconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v0.9.0  enabled  OK
        dask-labextension v2.0.0  enabled  OK
        jupyterlab-nvdashboard v0.1.9  enabled   X

   The following extension are outdated:
        jupyterlab-nvdashboard

   Consider running "jupyter labextension update --all" to check for updates.
```

**Comment by andersy005** [comment]
P.S.: I downgraded bokeh to `v1.4.0`, and everything seems to be working just fine.

**Comment by mrocklin** [comment]
cc @bryevdv in case he has suggestions on where to look

**Comment by bryevdv** [comment]
Bokeh 2.0 was a major number bump with breaking changes. A general migration guide is here:

https://docs.bokeh.org/en/latest/docs/releases.html#release-2-0-0

If you are talking directly to a Bokeh WS handler (was definitely not aware anyone anywhere was doing this) then there will be other adjustments to make. The Bokeh server websocket handler now expects sub-protocol specific + a token.  The best source of truth is this PR:

https://github.com/bokeh/bokeh/pull/9791

Probably most especially the changes here:

https://github.com/bokeh/bokeh/pull/9536/files#diff-03996256f9948165f2fffa4a6474e0c1

**Comment by jacobtomlinson** [comment]
We should put out a bugfix release which pins bokeh to `<2`.

Then look at addressing these changes.

**Comment by jacobtomlinson** [comment]
Just pushed a release `2.0.1` which pins bokeh to less that v2. So new installs should work again.

I'll leave this issue open as we now should embrace the API changes in bokeh.

**Comment by xhochy** [comment]
The problem lies within `jupyter-server-proxy` and is fixed in https://github.com/jupyterhub/jupyter-server-proxy/pull/180

**Comment by jacobtomlinson** [comment]
Thanks @xhochy. Let us know when you next release.

**Comment by xhochy** [comment]
I friendly asked for a release: https://github.com/jupyterhub/jupyter-server-proxy/pull/180#issuecomment-603236097 I'm no maintainer of that.

**Comment by scottyhq** [comment]
@jacobtomlinson - is it possible to do a 2.0.2 release that reverts the bokeh pin, but bumps jupyter-server-proxy>1.3.0? Maybe it's not so simple and there are other reasons to keep bokeh<2 ...

I ran into this incompatibility today trying to install alongside the latest panel library which requires bokeh>2
https://github.com/holoviz/panel/blob/ac0be10684b8c9260ad2f298eeeb08f139c00ace/setup.py#L92

**Comment by quasiben** [comment]
Jacob will be out for a bit.   @scottyhq I don't think it would be safe to revert until after bokeh>=2 has been tested and validated to work

**Comment by TomAugspurger** [comment]
IIRC the plan on the distributed side is to exclude bokeh==2.0.0, and allow
older or newer.

**Comment by jsignell** [comment]
I just did a mild test of bokeh 2.0.1 with jupyter-server-proxy 1.3.2  and things seem to be working fine. Were there particular failures that people had noticed? Otherwise it seems like we can update the pins.
