### ISSUE TITLE
Support dark mode in dask graph

### ISSUE THREAD

**Issue by drorspei** [dask/dask-labextension#127]
Hi hi
Small issue:
Edges in the dask graph are invisible when in dark mode.
Is it possible to make them light grey when in dark mode?

Example graph in dark mode:
![image](https://user-images.githubusercontent.com/18491610/80389290-8fb8d500-88b3-11ea-957b-ef77c64481f8.png)

Same graph in light mode:
![image](https://user-images.githubusercontent.com/18491610/80389340-9b0c0080-88b3-11ea-9dd6-3fcfd8456b69.png)

**Comment by TomAugspurger** [comment]
These changes would need to be made in `dask/distributed` rather than `dask-labextension`.

We have an issue for it at https://github.com/dask/distributed/issues/2305.
