### ISSUE TITLE
Dask Kubernetes Issue (jupyter-server-proxy >= 1.2.0)

### ISSUE THREAD

**Issue by iwalmsley** [dask/dask-labextension#129]
**Dask Labextension Version**: 2.0.2
**Dask Version**: 2.15
**Dask Kubernetes Version**: 0.10

First off apologies if this isn't related to the Dask Labextension directly, but that's where I'm seeing the issue - if not if you could point me in the right direction that'd be great.

Have recently come across an issue with the Dask labextension when after updating our Docker images all of the graph links (Task Stream, Progress) etc are all greyed out after creating a cluster on Kubernetes. The cluster itself is spun up fine, however still can't access the graphs, when looking at the network tab there's a 403 for;

https://notebook.domain/dask/dashboard/ba076ca2-49be-4262-b4a2-c4ff39eeb2d6/individual-plots.json?1589202704253

When I browse to this I get an error presumably from jupyter-server-proxy;

> Host '10.42.3.219' is not whitelisted. See https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports-hosts.html for info.

Which is the IP address of the JupyterLab pod. This indicates that the pod's IP needs to be in the ServerProxy.host_whitelist, but I don't understand why this request isn't being recognised from 127.0.0.1/localhost? Additionally I haven't been able to get it working even after adding this IP into the whitelist anyway.

If anyone could point me in the right direction that'd be great. Thanks in advance.

**Comment by TomAugspurger** [comment]
What version of distributed did you update to? There were some issues with distributed 2.15.0 and 2.15.1.

**Comment by jacobtomlinson** [comment]
Gently nudge to @iwalmsley to try again with newer versions.

**Comment by jsignell** [comment]
Closing this for now. @iwalmsley if you are still encountering this issue please reopen.
