### ISSUE TITLE
404 error plus buttons disappearing

### ISSUE THREAD

**Issue by lmsanch** [dask/dask-labextension#133]
I am trying to run the same simple example in the video, however, I am experiencing multiple problems.

Running the example without any visualization runs fine.
![Screenshot from 2020-06-22 15-44-34](https://user-images.githubusercontent.com/3156487/85329144-f3b8dd80-b49f-11ea-829e-81a95414856a.png)

Going to the Dask tab and pressing "+ new" successfully creates a new cluster, but the visualization options disappear.

![Screenshot from 2020-06-22 15-43-36](https://user-images.githubusercontent.com/3156487/85329225-18ad5080-b4a0-11ea-92c0-1a513ff4f318.png)

Manually going to the dashboard URL returns 404 error.

I am in a conda environment, and have I have uninstalled, installed, upgraded, restarted, etc. my machine many times and still can't figure out what's happening. The specs of my machine are here:

![Screenshot from 2020-06-22 15-55-25](https://user-images.githubusercontent.com/3156487/85329622-ddf7e800-b4a0-11ea-8756-aec8ca0bb4ad.png)

I am using python 3.7.7. This is what I have in my conda base environment:
aiohttp==3.6.2
alabaster==0.7.12
alembic==1.4.2
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
argh==0.26.2
asn1crypto==1.3.0
astroid==2.3.3
astropy==4.0.1.post1
async-generator==1.10
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==19.3.0
autopep8==1.4.3
Babel==2.8.0
backcall==0.2.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.9.1
bitarray==1.2.2
bkcharts==0.2
bleach==3.1.5
blinker==1.4
bokeh==2.1.0
boto==2.49.0
Bottleneck==1.3.2
brotlipy==0.7.0
cached-property==1.5.1
cachetools==4.1.0
certifi==2020.6.20
certipy==0.1.3
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cloudpickle==1.4.1
clyent==1.2.2
colorama==0.4.3
conda==4.8.3
conda-build==3.18.11
conda-package-handling==1.7.0
contextlib2==0.6.0.post1
correlation-cuda==0.0.0
cryptography==2.9.2
cvxopt==1.2.3
cycler==0.10.0
Cython==0.29.20
cytoolz==0.10.1
dask==2.18.1
dask-labextension @ file:///home/conda/feedstock_root/build_artifacts/dask-labextension_1588177406011/work
deap==1.2.2
decorator==4.4.2
defusedxml==0.6.0
depthflowprojection-cuda==0.0.0
df2gspread==1.0.4
diff-match-patch==20181111
distributed==2.18.0
docker==3.6.0
docker-compose==1.23.2
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
filterinterpolation-cuda==0.0.0
flake8==3.7.9
Flask==1.1.2
flowprojection-cuda==0.0.0
fsspec==0.7.4
future==0.18.2
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
google-api-python-client==1.6.7
google-auth==1.14.1
google-auth-oauthlib==0.4.1
greenlet==0.4.16
gspread==3.5.0
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
httplib2==0.17.3
hyperopt==0.1.1
hypothesis==5.16.1
ibm-cloud-sdk-core==1.0.0
ibm-watson==4.0.4
idna==2.9
imageio==2.8.0
imagesize==1.2.0
imbalanced-learn==0.6.2
importlib-metadata==1.6.1
interpolation-cuda==0.0.0
interpolationch-cuda==0.0.0
intervaltree==3.0.2
ipykernel==5.3.0
ipython @ file:///tmp/build/80754af9/ipython_1592348411427/work
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.15.2
jeepney==0.4.3
Jinja2==2.11.2
joblib==0.15.1
json5==0.9.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyter-server-proxy @ file:///home/conda/feedstock_root/build_artifacts/jupyter-server-proxy_1590048206892/work
jupyter-telemetry==0.0.5
jupyterhub==1.1.0
jupyterlab==2.1.4
jupyterlab-server==1.1.5
keyring==21.1.1
kiwisolver==1.2.0
lazy-object-proxy==1.5.0
libarchive-c==2.9
lightgbm==2.2.2
llvmlite==0.32.1
locket==0.2.0
lxml==4.5.1
Mako==1.1.0
MarkupSafe==1.1.1
matplotlib @ file:///tmp/build/80754af9/matplotlib-base_1592406090020/work
mccabe==0.6.1
mindepthflowprojection-cuda==0.0.0
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.0
mkl-service==2.3.0
mlxtend==0.17.0
mock==4.0.2
more-itertools==8.4.0
mpmath==1.1.0
msgpack==1.0.0
multidict==4.7.6
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.7
networkx==2.4
nltk @ file:///tmp/build/80754af9/nltk_1592496090529/work
nose==1.3.7
notebook==6.0.3
numba==0.49.1
numexpr==2.7.1
numpy==1.18.1
numpydoc==1.0.0
oauth2client==4.1.3
oauthlib==3.1.0
olefile==0.46
openpyxl==3.0.3
packaging==20.4
pamela==1.0.0
pandas==1.0.4
pandocfilters==1.4.2
parso==0.5.2
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
pkginfo==1.5.0.1
plotly==4.2.1
pluggy==0.13.1
ply==3.11
prometheus-client==0.8.0
prompt-toolkit==3.0.5
psutil==5.7.0
ptyprocess==0.6.0
py==1.8.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.20
pycrypto==2.6.1
pycurl==7.43.0.5
pydocstyle==4.0.1
pyflakes==2.1.1
Pygments==2.6.1
PyJWT==1.7.1
pylint==2.4.4
pymongo==3.9.0
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.16.0
PySocks==1.7.1
pytest==5.4.3
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.7.0
pytest-openfiles==0.5.0
pytest-remotedata==0.3.2
python-dateutil==2.8.1
python-dotenv==0.10.3
python-editor==1.0.4
python-json-logger==0.1.11
python-jsonrpc-server==0.3.4
python-language-server==0.31.10
pytz==2020.1
PyWavelets==1.1.1
pyxdg==0.26
PyYAML==5.3.1
pyzmq==18.1.1
QDarkStyle==2.8.1
QtAwesome==0.7.2
qtconsole==4.7.4
QtPy==1.9.0
regex==2020.5.14
requests==2.23.0
requests-oauthlib==1.3.0
retrying==1.3.3
rope==0.17.0
rrcf==0.3.2
rsa==4.0
Rtree==0.9.4
ruamel-yaml==0.15.87
ruamel.yaml.clib==0.2.0
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.1
SecretStorage==3.1.2
selenium==3.141.0
Send2Trash==1.5.0
separableconv-cuda==0.0.0
separableconvflow-cuda==0.0.0
shap==0.35.0
simpervisor==0.3
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.15.0
snowballstemmer==2.0.0
sortedcollections==1.2.1
sortedcontainers==2.2.2
soupsieve==2.0.1
Sphinx==3.0.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport==1.2.1
spyder==4.1.3
spyder-kernels==1.9.1
SQLAlchemy==1.3.17
statsmodels==0.11.1
stopit==1.1.2
sympy==1.6
TA-Lib==0.4.18
tables==3.6.1
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
texttable==0.9.1
toolz==0.10.0
torch==1.5.0
tornado==6.0.4
TPOT==0.10.2
tqdm==4.46.1
traitlets==4.3.3
typed-ast==1.4.0
typing-extensions==3.7.4.1
ujson==1.35
unicodecsv==0.14.1
update-checker==0.16
uritemplate==3.0.1
urllib3==1.25.9
watchdog==0.10.2
wcwidth==0.2.4
webencodings==0.5.1
websocket-client==0.48.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wit==5.1.0
wrapt==1.12.1
wurlitzer==2.0.0
xgboost==0.90
xlrd==1.2.0
XlsxWriter==1.2.9
xlwt==1.3.0
xmltodict==0.12.0
yapf==0.28.0
yarl==1.4.2
zict==2.0.0
zipp==3.1.0

Any insights into what might be causing the problem?

**Comment by TomAugspurger** [comment]
Can you try distributed 2.19.0? There was a compatibility issue with distributed 2.18 and some versions of bokeh.

**Comment by lmsanch** [comment]
Thank you @TomAugspurger . What would be the safest way to do this in anaconda environment? uninstall everything and install specific packages? pip install --upgrade distributed?  Cheers

**Comment by TomAugspurger** [comment]
conda install distributed would get it when it's available in your channels
(defaults by default, conda-forge if you've added it).
