### ISSUE TITLE
Dashboard not activated after starting dask distributed cluster.

### ISSUE THREAD

**Issue by statiksof** [dask/dask-labextension#144]
**What happened**:

The dashboard is not active and remains grey even if the client started normaly.

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client
client = Client()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2.22.0
- Python version: 3.6.10
- Jupyterhub: 1.1.0
- Install method: conda -c conda-forge

**Config**:
- ```distributed.yaml```

```
#   ###################
#   # Bokeh dashboard #
#   ###################

   dashboard:
     link: "/user/{JUPYTERHUB_USER}/proxy/{port}/status"
#     export-tool: False

```

**Comment by jacobtomlinson** [comment]
What happens if you click the magnifying glass icon in the extension? Does it discover the cluster URL?

![image](https://user-images.githubusercontent.com/1610850/89639104-e7001580-d8a4-11ea-9eb0-316f56da1aad.png)

**Comment by statiksof** [comment]
@jacobtomlinson I see  ```/user/user1/proxy/8787/status```. 
Just for information, this worked some time ago and I didn't upgrade anything.

**Comment by statiksof** [comment]
I tried to remove the text from the DASK DASHBOARD URL, restarted the cluster, clicked again on glass icon, it did not discover the Cluster URL.

**Comment by jacobtomlinson** [comment]
Ok thanks for the info. What does `client.cluster.dashboard_address` give?

**Comment by jacobtomlinson** [comment]
It might be `dashboard_link` actually.

**Comment by statiksof** [comment]
Do you mean ```client.dashboard_link```? because 
`client.cluster.dashboard_address` didn't work.
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-1372a92856b7> in <module>
----> 1 client.cluster.dashboard_address

AttributeError: 'LocalCluster' object has no attribute 'dashboard_address'
```

Output of ```client.dashboard_link``` is ```/user/user1/proxy/8787/status```

**Comment by jacobtomlinson** [comment]
And if you put `/user/user1/proxy/8787/status` into the box in the extension and press enter what happens?

**Comment by ian-r-rose** [comment]
Hi @statiksof, is this a new issue? We published a 3.0 release yesterday that requires a recent version of `distributed`. Can you try upgrading that?

**Comment by statiksof** [comment]
> Hi @statiksof, is this a new issue? We published a 3.0 release yesterday that requires a recent version of `distributed`. Can you try upgrading that?

I am already using 3.0.0 with distributed 2.20.0.

**Comment by statiksof** [comment]
> And if you put `/user/user1/proxy/8787/status` into the box in the extension and press enter what happens?

Nothing happened, they didn't change the colour. I tried `jupyter lab clean` and `build`, I see no warning/error in the log. The extension detects the cluster but it does not activate.

Even if I only have `distributed.yaml` to change the dashboard url, is there a way to purge/rempve any other dark configuration on my `$HOME`?

**Comment by devsentient** [comment]
I'm having the same issue but with a kubernetes dask cluster. It starts normally through the jupyter lab extension and I can scale the workers up and down, but can't access the dashboard. The buttons are greyed out. If I press the magnifying glass, it populates the IP address of the pod that's running jupyter lab with 8787 port, but the buttons are still grey.

**Comment by devsentient** [comment]
Update: i just tried `/user/username/proxy/8787/status` and it worked. However, that's not what the extension populates by default

**Comment by statiksof** [comment]
Is there a way to remove all dask/distributed ... config from $HOME? maybe something is conflicting.

**Comment by jacobtomlinson** [comment]
@devsentient how did you deploy your cluster? It sounds like some config is missing.

@statiksof the [config documentation](https://docs.dask.org/en/latest/configuration.html) lists the locations where config is stored. I would check those places for errant config.

**Comment by statiksof** [comment]
@jacobtomlinson removed any config file, still not working. In Javascript console I see this:

`/user/user1/proxy/8787/status does not appear to host a valid Dask dashboard`

**Comment by statiksof** [comment]
@jacobtomlinson @ian-r-rose my bad, the url of the notebook changed so the dashboard url was not correct. Everything works fine now with all latest versions.
