### ISSUE TITLE
Follow redirect in search box

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#158]
For some reason my dashboard redirects from `/` to some other address.  When I press the magnifying glass button the Dask-JLab extension doesn't work.  But when I take this address, copy it into a web browser, let that handle the redirect, and then copy it back, everything works smoothly.

**Comment by ian-r-rose** [comment]
Do you have an environment which reproduces this redirect? We could try to flip the `follow_redirects` switch to `True` in the tornado proxy handler. I can't think of a downside to doing that at the moment.

**Comment by mrocklin** [comment]
My experience is that this happens with any cluster made by Coiled.

Background here is that we serve the dashboard both through a normal HTTP
endpoint at some ec2 address, and proxied through our own proxy.  The
proxied address has a prefix like /dashboard/####/ and that gets passed to
the normal HTTP/EC2 situation as well.

**Comment by ian-r-rose** [comment]
One thing I've been thinking about for a while that might fix this: when the user pastes a dashboard URL into the search bar, that is directly checked by the browser client to see if it hosts a dashboard, and the iframe URLs are directly constructed from it. We've done this largely for reasons having to do with history and simplicity (i.e., before the server-side component of this extension existed). There have been a lot of problems with that approach, however:

* It involves a lot of spammy checks to possibly invalid or down URLs (e.g. #43)
* It has a pretty hacky check for a static image to get around CORS and mixed content issues
* It can't follow redirects, as in this issue.

It may be time to do a round-trip with the user supplied dashboard URL to the server extension. This would allow us to check for validity without doing any weird CORS workarounds, and we could follow redirects to the actual bokeh server URL, returning that to the client for iframing.
