### ISSUE TITLE
Dask server error on Centos7

### ISSUE THREAD

**Issue by karthik2527** [dask/dask-labextension#163]
**What happened**:

Unable to utilise Dask extension, couldn't launch a new cluster. 

Seeing Dask Server error - Failed to list cluster: might the server extension not be installed/enabled? during the launch of JupyterLab. 

**What you expected to happen**:

JupyterLab UI is expected to open without any errors and user should be able to spin up a new dask cluster. 

**Minimal Complete Verifiable Example**:

```Dockerfile
# # Install JupyterLab extensions for Dask. Then clean up build artifacts left over.
 RUN conda install --freeze-installed -c conda-forge dask-labextension==2.0.2 \
  && jupyter labextension install  --no-build \
     dask-labextension@2.0.2 \
     @jupyter-widgets/jupyterlab-manager@2.0.0 \
     jupyter-matplotlib@0.7.2 \
  && jupyter lab build --dev-build=False --minimize=False \
  && jupyter lab clean \
  && jlpm cache clean \
  && npm cache clean --force \
  && pip check \
  && conda clean -y -a \
```

**Anything else we need to know?**:

[user@c8691feb0e27 ~]$ jupyter serverextension list
config dir: /opt/anaconda3/etc/jupyter
dask_labextension enabled
- Validating...
Error loading server extension dask_labextension
X is dask_labextension importable?
jupyter_server_proxy enabled
- Validating...
Error loading server extension jupyter_server_proxy
X is jupyter_server_proxy importable?
jupyterlab enabled
- Validating...
jupyterlab 2.0.1 OK
nb_conda enabled
- Validating...
nb_conda 2.2.1 OK
(base) [user@c8691feb0e27 ~]$

 [user@c8691feb0e27 ~]$ conda list dask
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /opt/anaconda3/conda-meta/numpy-base-1.19.2-py37hfa32c7d_0.json. Please remove this file manually (you may need to reboot to free file handles)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename /opt/anaconda3/conda-meta/dask-core-2020.12.0-pyhd3eb1b0_0.json. Please remove this file manually (you may need to reboot to free file handles)
# packages in environment at /opt/anaconda3:
#
# Name Version Build Channel
dask 2.15.0 pypi_0 pypi
dask-labextension 2.0.2 py_0 conda-forge
(base) [user@c8691feb0e27 ~]$

<img width="1680" alt="UI-Error" src="https://user-images.githubusercontent.com/59581385/103583401-8d455b00-4ed7-11eb-9e6e-7cb2df02b47e.png">

**Environment**: Centos 7 docker container

- Dask version: dask 2.15.0 pypi_0 pypi
- Python version: 3.7.6.final.0
- Operating System: Centos 7
- Install method (conda, pip, source): conda

**Comment by ian-r-rose** [comment]
Hmm the fact that `dask_labextension` is unable to validate when listing serverextensions (as well as `jupyter-server-proxy`) is a problem. What happens if you try to import it manually in a Python session?

**Comment by karthik2527** [comment]
It gives below errors, 

`(base) [user@a4c7a3db80bd ~]$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask
>>> import dask_labextension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/dask_labextension/__init__.py", line 7, in <module>
    from .dashboardhandler import DaskDashboardHandler
  File "/opt/anaconda3/lib/python3.7/site-packages/dask_labextension/dashboardhandler.py", line 11, in <module>
    from jupyter_server_proxy.handlers import ProxyHandler
  File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_server_proxy/__init__.py", line 1, in <module>
    from .handlers import setup_handlers, SuperviseAndProxyHandler
  File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 11, in <module>
    import aiohttp
  File "/opt/anaconda3/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/opt/anaconda3/lib/python3.7/site-packages/aiohttp/client.py", line 33, in <module>
    from yarl import URL
  File "/opt/anaconda3/lib/python3.7/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/opt/anaconda3/lib/python3.7/site-packages/yarl/_url.py", line 58, in <module>
    @rewrite_module
  File "/opt/anaconda3/lib/python3.7/site-packages/yarl/_url.py", line 131, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
>>> `

**Comment by ian-r-rose** [comment]
Looks like the problem is in `yarl`. What version of that do you have? Perhaps try upgrading it?

**Comment by karthik2527** [comment]
Upgraded yarl==1.6.3 worked, wonderful suggestion. Thank you very much.

**Comment by ian-r-rose** [comment]
Great, thanks for the update @karthik2527
