### ISSUE TITLE
Help setting up a development environment

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-labextension#177]
I'm struggling to set up my development environment since the move to Jupyter Lab 3. I followed the guide to set up my development environment as per the README instructions but I am struggling to get an editable install.

MCRE:

- `cd /tmp`
- `git clone git@github.com:dask/dask-labextension.git`
- `cd dask-labextension`
- `conda create -n daskjupyterdebug -c conda-forge python=3.8 ipython jupyterlab -y`
- `conda activate daskjupyterdebug`
- `jlpm`
- `jlpm build`
- `jupyter labextension develop . --overwrite`

This last step fails with `ModuleNotFoundError: There is not a labextensions at .`.

If I launch Jupyter Lab the extension appears to be installed, but if I make modifications and run `jlpm build` I don't see them reflected after relaunching Jupyter Lab.

Also if I list extensions it appears I have the latest release installed instead.

```
$ jupyter labextension list                 
JupyterLab v3.0.9
/Users/jtomlinson/miniconda3/envs/daskjupyterdebug/share/jupyter/labextensions
        dask-labextension v5.0.1 enabled OK (python, dask_labextension)
```

What am I doing wrong?

**Comment by ian-r-rose** [comment]
Thanks for flagging this @jacobtomlinson, I can reproduce your issue. You haven't done anything wrong -- instead it looks like I missed a step to get editable installs working in #162 (thought non-editable installs should still work locally). I'll whip up a fix
