### ISSUE TITLE
Remove default dashboard plots

### ISSUE THREAD

**Issue by ian-r-rose** [dask/dask-labextension#198]
This extension gets its list of dask dashboard plots by querying the dashboard's `individual-plots.json` endpoint. These are then shown to the user as the orange buttons in the extension side bar. If, however, that request to `individual-plots.json` fails, we show a default listing, given by this:

https://github.com/dask/dask-labextension/blob/365913b4f77910e75f5e60114d44f5785b762db7/src/dashboard.tsx#L439-L464

Historically, these default items were useful because we were checking for the `individual-plots.json` from the browser side. This request could fail for a valid dashboard URL (often for CORS-related reasons), and having the fallback meant that we could still iframe useful plots for the user. However, since #159 we are checking for `individual-plots.json` on the server side, which is not subject to the same restrictions as the browser. So as it stands today, the default items are mostly (only?) used to show the greyed out buttons when no dask dashboard is connected.

As the dask dashboard evolves, gains new plots, renames things, etc, it has become annoying to keep the default listing up-to-date. Furthermore, different scheduler plugins or distributions of dask could add different dashboards. So there really isn't much guarantee that the default listing is particularly accurate. We should consider removing them entirely, and just show something like a "No dashboard connected" info box.

Would anybody miss the grey buttons?

**Comment by jrbourbeau** [comment]
I wouldn't miss the greyed out buttons. Additionally, as you already mentioned, it would make renaming plots (xref https://github.com/dask/distributed/pull/4878) easier

**Comment by jacobtomlinson** [comment]
Agree I wouldn't miss the greyed out buttons.

**Comment by jacobtomlinson** [comment]
Once this is done we should also remove this backward compatibility in distributed.

https://github.com/dask/distributed/blob/97f10b196c2fc6f68aeb8858c4733267b12eafb6/distributed/dashboard/scheduler.py#L67-L71
