### ISSUE TITLE
Sort order of plots

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#199]
Right now they seem to come up in random order and this changes every time

![image](https://user-images.githubusercontent.com/306380/126051902-967fcca0-aa90-463d-b0a5-570dd72ece9a.png)
![image](https://user-images.githubusercontent.com/306380/126051916-fbc3cf00-7fc6-4aad-ae90-012c5a9bdb86.png)

Probably sorting by alphabetical ordering would be a positive change

**Comment by ian-r-rose** [comment]
Agreed, this is pretty straightforward. See also #179 with a suggestion to vary the colors to make the charts easier to pick out.
