### ISSUE TITLE
How to record dashboard layout within new installations

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#20]
So, for tutorials or science setups with JupyterHub I'd like to be able to provide users with a pre-defined layout of panes and dashboard link on startup.  These seem to be saved locally on my machine somehow.  Is there a way to set these up and then persist a file somewhere with the information inside a docker container?

**Comment by ian-r-rose** [comment]
You can save the layout in a named "workspace" by going to `/lab/workspaces/mylayout`. This is stored in a workspaces directory on disk (you can find this by doing `jupyter lab path`). This workspace file can be used to seed a tutorial container.

We are working on a basic CLI to allow people to more easily export/import workspace files (so you won't have to copy files around the file system), but for the moment it's a bit awkward.

**Comment by ian-r-rose** [comment]
xref: jupyterlab/jupyterlab#5166

**Comment by rpanai** [comment]
@ian-r-rose  I supposed was [this](https://github.com/dask/dask-examples/blob/852a0dd706f5e5f4b9ad4e8079ebc508a6419342/binder/start)

**Comment by ian-r-rose** [comment]
Yes, that will work, but we are still waiting on jupyterlab/jupyterlab#5166 which will make the process a bit smoother and less error-prone.

**Comment by ian-r-rose** [comment]
I believe this is solved by dask/dask-examples#49
