### ISSUE TITLE
Remove "Dask " from the titles of tabs

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#201]
My JLab panes look like this:

![Screen Shot 2021-07-20 at 6 29 31 AM](https://user-images.githubusercontent.com/306380/126332496-736cb639-97bb-4577-8b4c-593fd4511051.png)

If we removed the word Dask from all of the titles then it would be easier to see what was what.  We already have the icon to distinguish these from other kinds of tabs.

**Comment by ian-r-rose** [comment]
Agreed, the icon should suffice.

A fairly simple fix, requires updating the labels here: https://github.com/dask/dask-labextension/blob/3e35dd277e503e13dfb0950379eab1400abcd729/src/index.ts#L192-L194

and here:
https://github.com/dask/dask-labextension/blob/3e35dd277e503e13dfb0950379eab1400abcd729/src/index.ts#L389

**Comment by mrocklin** [comment]
Should I interpret this last comment as "this is easy so I'll do it soon" or "this is easy so it might be a good opportunity to bring in some new".  If the latter, Alex?

**Comment by ian-r-rose** [comment]
I'm happy to do it soon (it is indeed very easy), but I'm also happy to bring on any extra hands. I suppose I intended it as a flare to see if any interested contributors popped up.

**Comment by mrocklin** [comment]
Go silent masses go!

**Comment by GenevieveBuckley** [comment]
silent masses, lol

Well, I came over here to complain about something (and find out that Ian has *already* fixed it, fantastic), so I may as well fix someone else's frustration while I'm here instead.
