### ISSUE TITLE
Fresh install, can't figure out how to view

### ISSUE THREAD

**Issue by stsievert** [dask/dask-labextension#21]
I've installed this extension with the extension manager in Jupyterlab 0.34.7.

<img width="233" alt="screen shot 2018-09-01 at 2 43 54 pm" src="https://user-images.githubusercontent.com/1320475/44949369-6d8d5c00-ae1f-11e8-9625-eedd20df598a.png">

When I try to view the panes dask-labextension presents, I see greyed out buttons:

<img width="522" alt="screen shot 2018-09-01 at 2 46 46 pm" src="https://user-images.githubusercontent.com/1320475/44949397-df65a580-ae1f-11e8-874e-1ed035546472.png">

When I try to drag them or double click on them, nothing happens. I've tried changing "Dask Dashboard URL" to `http://127.0.0.1/status`, the value presented by `client`.

How do I view the panes dask-labextension presents?

**Comment by stsievert** [comment]
I tried that, but no luck. When I start up JupyterLab, I get a message

``` shell
# right below "Copy/paste this URL into your browser when you connect ..."
[W 18:56:10.034 LabApp] 404 GET /lab/api/settings/jupyterlab-dask:plugin?1535846169700 (::1): Schema not found: '/Users/scott/anaconda3/share/jupyter/lab/schemas/jupyterlab-dask/plugin.json'
[W 18:56:10.035 LabApp] Schema not found: '/Users/scott/anaconda3/share/jupyter/lab/schemas/jupyterlab-dask/plugin.json'
[W 18:56:10.037 LabApp] 404 GET /lab/api/settings/jupyterlab-dask:plugin?1535846169700 (::1) 4.93ms referer=None
```

When I visit `/Users/scott/anaconda3/share/jupyter/lab/schemas/`, I see a directory named `dask-labextension`, not `jupyterlab-dask`. `dask-labextension` contains `plugin.json`

It looks like Jupyter is looking for a directory `jupyterlab-dask`, not `dask-labextension`. I tried copy/pasting `dask-labextension` to `jupyterlab-dask`. That got rid of the error message above, but didn't resolve the issue (the buttons are still greyed out).

**Comment by dhirschfeld** [comment]
I also can't get this extension to work.

I also get a 404 on `jupyterlab-dask`
```
/user/dhirschfeld/lab/api/settings/jupyterlab-dask:plugin?1535956133900 404 (Not Found)
```

When I enter the dask dashboard url it then says it's not valid:
```
widget.js:130 http://server:59863 does not appear to host a valid Dask dashboard
d.testDaskDashboard.then.r @ widget.js:130
Promise.then (async)
set url @ widget.js:123
handleEvent @ widget.js:179
```
...and I receive a lot to CORB errors
```
18 Cross-Origin Read Blocking (CORB) blocked cross-origin response <URL> with MIME type text/html. See <URL> for more details.
```
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://server:59863/statics/images/dask-logo.svg?1535956405943 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by ian-r-rose** [comment]
Thanks for the reports @stsievert and @dhirschfeld, it looks like the problems you are running into are a result of some of the waffling I had regarding the name of the extension. I'm working up a fix right now.

**Comment by ian-r-rose** [comment]
@dhirschfeld we are aware that there are potential CORS issues, and are still thinking through what best-practices for those should be. You might try something similar to what is done in [this](https://github.com/pangeo-data/pangeo-example-notebooks/blob/master/binder/start) example with `nbserverproxy`, which proxies the dashboard to be under the notebook server origin.

**Comment by dhirschfeld** [comment]
Thanks @ian-r-rose. I've been meaning to check out `nbserverproxy` so I'll bump that up the priority list!

Currently users have access to the dask cluster from the enterprise network but that may not always be the case so I had thought to use `nbserverproxy` to work around that restriction in any case
