### ISSUE TITLE
Long plot names

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-labextension#211]
In https://github.com/dask/distributed/pull/5129 we added a new "Workers network bandwidth timeseries" plot. I noticed that when the labextension sidebar is small, this plot's name is large enough that its text doesn't fit inside the corresponding button:

<img width="408" alt="Screen Shot 2021-08-19 at 3 53 51 PM" src="https://user-images.githubusercontent.com/11656932/130151500-f101b681-5ffc-4a56-9d02-0a783b3f95a0.png">

A couple of things we might consider:

1. We can change the plot's name in `distributed` (e.g. drop the word "bandwidth" or "network"). However, as we make new plots in the future, some longer names might slip through. I suppose we could always add some test in `distributed` that plot names must be below X characters
2. I'm wondering if there's anything we can do in the labextension to dynamically change the name that's displayed based on the size of the sidebar (e.g. adding ellipsis like "Worker network bandwidth tim...").
3. ... something else? 

cc @ncclementi for visibility

**Comment by mrocklin** [comment]
I think that short term we should use a more concise naming scheme and that
long term we should have categories in the labextension buttons to help
with hierarchy

**Comment by ncclementi** [comment]
This is a quick fix I can take care of by modifying the name on distributed, in these two lines

https://github.com/dask/distributed/blob/6a8b49db67896caeea1b6e6075c1dd50b45ae73b/distributed/dashboard/scheduler.py#L72

https://github.com/dask/distributed/blob/6a8b49db67896caeea1b6e6075c1dd50b45ae73b/distributed/dashboard/scheduler.py#L78

now, what do we want to remove "network" or "bandwidth" ? I'm curious what's the better name choice for the user to find the plot.

**Comment by ian-r-rose** [comment]
We can also do some things with CSS on the labextension side to wrap or clip long names (possibly with a hover for the full name)

**Comment by jrbourbeau** [comment]
> now, what do we want to remove "network" or "bandwidth" ?

I would drop "network" and go with "workers bandwidth"

**Comment by mrocklin** [comment]
Just "bandwidth" and "bandwidth timeseries" maybe?  I think that these are
likely the default

**Comment by ncclementi** [comment]
I noticed that we already have a plot called "Bandwidth Workers" I wonder how would we deal with this since it might cause confusion. 

![Screen Shot 2021-08-20 at 1 15 14 PM](https://user-images.githubusercontent.com/7526622/130270005-9645220b-4249-43f9-984b-4be05c23d623.png)

![Screen Shot 2021-08-20 at 1 18 33 PM](https://user-images.githubusercontent.com/7526622/130270381-e067a11e-43f9-4070-8804-7d118dbd0ca8.png)

Is this plot ever used? 

This is plotting the bandwidth information in `self.scheduler.bandwidth_workers` 
https://github.com/dask/distributed/blob/6a8b49db67896caeea1b6e6075c1dd50b45ae73b/distributed/dashboard/components/scheduler.py#L698

**Comment by jrbourbeau** [comment]
Ah, good point. That plot is [included in performance reports](https://github.com/dask/distributed/blob/6a8b49db67896caeea1b6e6075c1dd50b45ae73b/distributed/scheduler.py#L7289-L7298) currently. @mrocklin feel free to correct me if I'm wrong, but my understanding is that plot is useful and we should keep it around.

Maybe the new plots should be "workers network" and "workers network timeseries". That will fit within the labextension button and is consistent with other plot names (e.g. "workers disk", "workers CPU timeseries", etc.). We can reevaluate after the release later today

**Comment by ian-r-rose** [comment]
This is now fixed by  dask/distributed#5239
