### ISSUE TITLE
Optionally hide cluster manager

### ISSUE THREAD

**Issue by ian-r-rose** [dask/dask-labextension#218]
I've had a few conversations with people involved Pangeo-style and HPC-style deployments where the cluster manager UI in this extension doesn't work well with their workflows.

I'd of course love for it to work better for them, but a relatively simple ask in that circumstance has been to expose an option to hide the cluster manager.

**Comment by jacobtomlinson** [comment]
This seems totally reasonable.

In the future I'd prefer this to become a "make the cluster manager read only" option. That way when we have cluster discovery with dask-ctl we can still show clusters that the user can access, but without them being able to create new ones in the UI.

**Comment by ian-r-rose** [comment]
> In the future I'd prefer this to become a "make the cluster manager read only" option. That way when we have cluster discovery with dask-ctl we can still show clusters that the user can access, but without them being able to create new ones in the UI.

A read-only manager makes good sense to me, though to me it sounds different enough from this functionality that it could be a separate option, rather than replacing this one. Do you envision it to be mostly for UI purposes? Or would we actually try to enforce it at the permissions level? I'd prefer the latter to be the responsibility of `dask-ctl`.

An aside, I'd really like to make a push on incorporating `dask-ctl` in the next few weeks, if possible.

**Comment by jacobtomlinson** [comment]
I guess the main problem I would like to solve is helping users find clusters which have been created on their behalf. Tools like the Dask Helm Chart launch a Dask cluster alongside Jupyter. It's pretty common for custom IT and HPC systems to do this too. So having existing clusters just show up makes sense.

I guess my thought about it being read only would be that if an HPC system provided a cluster alongside a Jupyter session the user may expect the create buttons to create another identical cluster, but instead it would likely create a `LocalCluster` on the login node.

**Comment by ian-r-rose** [comment]
Makes sense to me. To be clear, I'm +1 on having a read-only option here. Do you think that metadata would something that `dask-ctl` would provide?

**Comment by jacobtomlinson** [comment]
What kind of metadata are you thinking?

**Comment by ian-r-rose** [comment]
I guess I'm thinking about something like "does the local user have permissions to manage cluster resources for a given cluster manager/provider?"

It's not obvious what we would do if there are multiple cluster provider/mananger implementations (the UI doesn't really envision that, but we could think about it)

**Comment by jacobtomlinson** [comment]
Interesting I hadn't put much thought into that. We should sync up soon to make plans to work on this.
