### ISSUE TITLE
Extension not working on GCP

### ISSUE THREAD

**Issue by rpanai** [dask/dask-labextension#24]
I'm trying to use this extension on the cloud without luck. How can I activate it?

**Comment by mrocklin** [comment]
I recommend saying more about exactly what you've tried and exactly why it
isn't working.

I don't think that there is anything about GCP in particular that would
interact with a JupyterLab extension.  I recommend trying things locally
first.

**Comment by rpanai** [comment]
@mrocklin see the followng screenshot. The buttons (Graph, ..., Workers) don't change color and I can't click them
![extension](https://user-images.githubusercontent.com/21178372/45178947-81eda200-b1ed-11e8-87c2-cc50404911bd.png)

**Comment by mrocklin** [comment]
You need to provide an address for the dashboard that your web client
(probably your laptop) can view.  dask-labextension does not proxy
connections.  You might also look into nbserverproxy.

**Comment by rpanai** [comment]
*You might also look into nbserverproxy* > I suspected so.

**Comment by ian-r-rose** [comment]
If it is a CORS issue you should see errors in the Javascript console (usually accessible using F12).

**Comment by rpanai** [comment]
@ian-r-rose I can see that on [binder](https://twitter.com/dask_dev/status/1039134493947453446) we can use this extension I'd love to have a similar solution when I work on the cloud.

**Comment by ian-r-rose** [comment]
Something very similar to what is done in the `dask-examples` binder could work for your use-case, since binder itself is run in the cloud.
