### ISSUE TITLE
No visibility (black background) with JupyterLab in Dark theme

### ISSUE THREAD

**Issue by JonnyTran** [dask/dask-labextension#242]
**What happened**:
With JupyterLab in Dark theme, the Bokeh dashboards doesn't have a white background so drawings are not visible.
<details>

![image](https://user-images.githubusercontent.com/4750391/190868156-0dd34547-9855-4156-9c6f-b2cb47e560fa.png)

</details>

**What you expected to happen**:
Bokeh dashboards should have a white plot background.

**Environment**:
JupyterLab 3.4.7
dask-labextension (pip install)

**Comment by ian-r-rose** [comment]
Thanks for the report @JonnyTran , there is some additional discussion [here](https://github.com/dask/distributed/issues/5200). I think the easiest fix would be to add a bit of explicit CSS to the background of the plot iframes. Would you be interested in submitting a PR?

**Comment by JonnyTran** [comment]
Sure! I'll take a look. If I have any questions I'll post it here or the orig [issue](https://github.com/dask/distributed/issues/5200).

**Comment by ian-r-rose** [comment]
Great! I think the easiest approach would be to create a new CSS class for the iframes [here](https://github.com/dask/dask-labextension/blob/main/style/index.css), and then to add that CSS class to the iframe widgets in the constructor here: https://github.com/dask/dask-labextension/blob/707ecb1dc0e4d0ef21e9cf57442db5768235dcd1/src/dashboard.tsx#L52-L62

There are other widgets in the same file that add CSS classes (using `addClass()`) that you can look to for examples.
