### ISSUE TITLE
Default layout

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#247]
This might not be a good idea but ...

Often when showing someone the Dask dashboard I ask them to set up a few windows, notably the task stream, progress, and workers memory.  I put these to the side of the notebook.  We even make this recommendation in the tutorial.

Would it make sense to codify this starter template somewhere?  Would it be possible to make a button for example that set these up?  

This is difficult I imagine because it's hard to reason about all of the other panes that may or may not be around.

**Comment by ian-r-rose** [comment]
This probably isn't too difficult to do on a best-effort basis. I'm sure there would be ways to come up with a nonsense layout if there are existing tabs open, but if you have a relatively simple starting state, it probably would work most of the time.

**Comment by mrocklin** [comment]
Hooray for best effort!

**Comment by mrocklin** [comment]
Thanks Ian!

**Comment by ian-r-rose** [comment]
This is now available in v6.0
