### ISSUE TITLE
Logos no longer working well

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#261]
```
mamba create -n test dask jupyterlab dask-labextension
jupyter lab
```

<img width="1181" alt="Screen Shot 2023-05-24 at 7 46 55 AM" src="https://github.com/dask/dask-labextension/assets/306380/74b7693f-a4b7-4511-9e68-ef5d2a69154a">

Notice both:

1.  The Dask logo on the side bar has a grey box behind it
2. The Dask logos in the Task Stream and Progress frames don't exist

cc @ian-r-rose in case you have time to look into this.  cc @jacobtomlinson and @dchudz (and team) in case he doesn't

```
(test) $ jupyter --version
Selected Jupyter core packages...
IPython          : 8.13.2
ipykernel        : 6.23.1
ipywidgets       : not installed
jupyter_client   : 8.2.0
jupyter_core     : 5.3.0
jupyter_server   : 2.5.0
jupyterlab       : 4.0.0
nbclient         : 0.8.0
nbconvert        : 7.4.0
nbformat         : 5.8.0
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.9.0
```

**Comment by mrocklin** [comment]
Things work fine if I install jupyterlab=3

**Comment by mrocklin** [comment]
Or @fjetter in case someone on your team has JS experience

**Comment by ian-r-rose** [comment]
Yeah, probably a Jlab 4 issue. I’ll try to look at it this weekend.

**Comment by dchudz** [comment]
@ian-r-rose if you have a chance to even just point us the right direction that'd be appreciated! Coiled folks don't have a ton of experience working on this, but we're happy to learn.
