### ISSUE TITLE
Inject client code adds an empty cell.

### ISSUE THREAD

**Issue by philippemiron** [dask/dask-labextension#265]
When I clicked the arrows `< >` to inject the client code from the `dask-labextension`, it includes an empty cells in the Notebook.

```
micromamba create --name test
micromamba activate test
micromamba install python=3.11 dask-labextension
jupyter-lab
```
Then
1. starts a local cluster from dask-labextension clusters bottom section
2. click the arrows `< >`
Then clicked the arrow.

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.6.1 
- Dask-labextension: 6.1.0
- Python version: 3.11
- Operating System: macOS Ventura 13.4.1 (ARM)
- Install method (conda, pip, source): conda-forge

**Comment by mahendrapaipuri** [comment]
This should be fixed in #263. Could you please try with the latest version of the extension `7.0.0`?

**Comment by philippemiron** [comment]
I can confirm it's working for me with 7.0.0.

**Comment by ian-r-rose** [comment]
Thanks for following up!
