### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-labextension#266]
Just wanted to follow up on https://github.com/dask/dask-labextension/pull/262#issuecomment-1594386972. I think it'd be good to get a release out with some of the recent fixes here (in particular the logo / plot title text updates). @ian-r-rose @jacobtomlinson do you think either of you would have time for a quick release? 

I'm also happy to give it a try, but haven't release this package before. I see there's https://github.com/dask/dask-labextension#publishing, but am not sure how up-to-date those instructions are.

**Comment by ian-r-rose** [comment]
Apologies for letting this drop! I'm happy to do a release. @jrbourbeau are you able to schedule a call to pair doing that and increase the bus factor a bit here?

> I'm also happy to give it a try, but haven't release this package before. I see there's https://github.com/dask/dask-labextension#publishing, but am not sure how up-to-date those instructions are.

Unfortunately the automated part of it is no longer running after the switch from Travis (we should remove that part).

**Comment by jrbourbeau** [comment]
No worries at all! I'm definitely available for a call to increase the bug factor. Just emailed you to set up a time (@jacobtomlinson let me if you want to join)

**Comment by ian-r-rose** [comment]
New release is out (6.2.0)
