### ISSUE TITLE
Warn if distributed version isn't new enough

### ISSUE THREAD

**Issue by stsievert** [dask/dask-labextension#27]
I installed this extension, but not with a `distributed==`0.17.5`. All the buttons were greyed out when I tried to use it. Updating to `distributed==0.19.2` resolved this and allowed me to use this extensions.

**Comment by stsievert** [comment]
With Python syntax, maybe something like

``` python
import requests

r = requests.get(dask_dashboard_url + '/individual-graph')
if r.status_code == 404:
    raise ValueError('This requires at least distributed==0.XX')
```

**Comment by ian-r-rose** [comment]
One difficulty: how would we distinguish between a version of distributed that is too old and an incorrect `dask_dashboard_url`? Both would result in 404 errors.

**Comment by stsievert** [comment]
Right. Maybe add a note if the buttons are greyed out? Something like
<img width="231" alt="screen shot 2018-10-04 at 9 14 53 pm" src="https://user-images.githubusercontent.com/1320475/46512725-fe06f400-c844-11e8-8406-10308b26570c.png">

**Comment by mrocklin** [comment]
There are some routes that go back decently far that would check if
desired.  We could also just fail for older versions.  I'm not
super-concerned about this.  I suspect that adopters of the labextension
will either be decently cutting edge (like @stsievert ) or will be provided
with canned environments (like pangeo).

**Comment by ian-r-rose** [comment]
Now that there is a server extension, this should be solved by pip-installing it. Closing as fixed.
