### ISSUE TITLE
Dashboard does not display graphs with bokeh = 3.3.0

### ISSUE THREAD

**Issue by andrewpauling** [dask/dask-labextension#270]
**Describe the issue**:
When trying to open the dask labextension within Jupyterlab running on JupyterHub, the graphs do not display with bokeh=3.3.0. If I roll back to bokeh=3.2.2 they work again. 

With bokeh=3.3.0 I get a bunch of errors in my jupyterhub log file with ConnectionRefusedError: [Errno 111] Connection refused

**Environment**:

- Dask version: 2023.10.1
- Python version:3.10.13
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by roxyboy** [comment]
Thanks for sharing this. I was facing the same issue with bokeh=3.3.2.

**Comment by jrbourbeau** [comment]
The `dask` + `distributed` 2023.12.0 release includes a few updates for `bokeh=3.3` compatibility. I'd recommended updating to see if that helps.

**Comment by jacobtomlinson** [comment]
Given the lack of response here I'm going to close this out. Please comment if you're still running into this and I can reopen it.
