### ISSUE TITLE
500 GET: missing dask-logo.svg

### ISSUE THREAD

**Issue by jhamman** [dask/dask-labextension#32]
I think this is the right place to put this issue. Happy to repost if not.

I'm running Jupyter Lab on a compute node without internet access, forwarding the interface through to my browser with ssh tunneling. 

As far as I can tell, everything is working but I am getting the error below every 2 seconds. I have the `dask-labextension` installed as well as `nbserverproxy`. Everything is up to date as of yesterday.

```
[E 12:39:53.359 LabApp] 500 GET /proxy/38753/statics/images/dask-logo.svg?1543520390075 (10.148.0.2) 2.79ms referer=http://localhost:8888/lab?
[E 12:39:55.361 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36",
      "Dnt": "1",
      "Accept": "image/webp,image/apng,image/*,*/*;q=0.8",
      "Referer": "http://localhost:8888/lab?",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|e448eca0|0b525a9a188b60ba2e504858d9d20a2f|1541648386; username-localhost-8888=\"2|1:0|10:1543519136|23:username-localhost-8888|44:ZDE4NmFiNWFmNjJkNGU0NmIyYWU0ZjU5NjQ4ZmRiNTg=|7e22ad6e8f01000cb4ec4cff1a01660ad181a4e2b848e8d66300483c718cefcc\""
    }
```

**Comment by mrocklin** [comment]
My guess is that Dask labextension queries that address every second to see if a cluster is alive there.  If it is then it connects up the existing plots.  

My guess is that we might want to wrap up the line that queries that file in whatever the TypeScript equivalent of a try-except block is.  It's ok to not find that address.

**Comment by mrocklin** [comment]
@ian-r-rose is my understanding above correct?

**Comment by jhamman** [comment]
My understanding is the fetch of this logo is being used to determine if the dashboard is up. So most of the behavior here seems correct, we probably just want to silence the error in some nice way. 
https://github.com/dask/dask-labextension/blob/2e743d9cfc43db5949a190788533c64b0fe288be/src/widget.tsx#L442-L453

**Comment by ian-r-rose** [comment]
Yes, @mrocklin, your understanding is right. The "logo fetching" has always been a hack, it is checking to see if the dashboard server is up and running while getting around some browser-security policies. I would love to be able to silence those errors, but I am not aware of a way to patch the tornado server to remove them.

@jhamman, I am rewriting the proxying logic in #31, so hopefully a lot of these issues will be solved (or greatly mitigated) there. In particular, once we have stronger guarantees that the cluster will be available under the same origin we will no longer need to check for the logo itself.

I am puzzled as to why it's a 500 error and not a 404, however... are there any other errors you see that might be relevant?

**Comment by jhamman** [comment]
```
[E 10:47:50.364 LabApp] 500 GET /proxy/8787/statics/images/dask-logo.svg?1544204869455 (10.148.0.4) 2.54ms referer=http://localhost:8888/lab
[W 10:47:52.458 LabApp] 404 GET /proxy/8787/status/individual-task-stream (10.148.0.4) 17.78ms referer=http://localhost:8888/lab
```

While futzing about with the app, we did see some 404 errors but they were only triggered by changing urls to the dashboard.  These could be related but I think the 404 comes up when the app cant find a dashboard it previously had found. The 500 errors come when the app hasn't found a dashboard at all yet.

**Comment by consideRatio** [comment]
In a JupyterHub, I end up with the following three different errors in the browsers console log. This is while I'm successfully running stuff against my Dask worker pods through the scheduler etc.

```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED dask-logo.svg:1

Failed to load resource: net::ERR_NAME_NOT_RESOLVED /user/erik.sundell/dask/clusters?1546445236329:1

Failed to load resource: the server responded with a status of 404 () clusters.js:5 
```
