### ISSUE TITLE
Automatically create client to current cluster in the background

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#35]
I'm interested in a workflow where users never have to create a Dask client, it just gets created for them silently in the background based on the current active Cluster in the server extension.  So an order of operations might look like the following:

1.  Open up JupyterLab
2.  Open up Notebook and ipython kernel
3.  Create cluster using the dask-labextension pane
4.  When we create that cluster it automatically creates a client in the notebook kernel without us doing anything.  All dask.compute calls automatically use that cluster/client
5.  Create a new cluster, have it automatically inject code to change the default client in the kernel
6.  Start a new kernel, either by creating a new notebook or by restarting your kernel
7.  The extension sees this and automatically injects code to create a new client

As a result, the user always uses the cluster specified in the labextension.  They have to explicitly choose *not* to use this if they want to use the local scheduler or a client of their own making.

This behavior would be off by default, but we could turn it on for things like tutorials, pangeo, and so on.

Is this useful, or is it too magical?

cc @ian-r-rose @jhamman @rabernat

**Comment by ian-r-rose** [comment]
Fixed by #36
