### ISSUE TITLE
Code-cell drag & drop functionality for cluster

### ISSUE THREAD

**Issue by dhirschfeld** [dask/dask-labextension#44]
The greedy/auto cluster client is a little too black-magic for my tastes but I think what would be very cool is if you could drag a cluster into a notebook and have it create a new code cell:
```python
import dask
from dask.distributed import Client

client = Client('tcp://address:port')
```

**Comment by ian-r-rose** [comment]
The auto-client may be a bit too much magic for my tastes as well :) (though I can see it being useful in some demos or institutional settings).

Drag/drop of connection code is definitely on my TODO list, but in the meantime, have you played with the "insert code" button on the cluster listing?

**Comment by dhirschfeld** [comment]
> *have you played with the "insert code" button on the cluster listing?*

I haven't yet - it's on my TODO! Currently bogged down in moving all our infrastructure onto kubernetes....
