### ISSUE TITLE
Adding package to conda-forge

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-labextension#45]
It would be great to have a conda-forge package for `dask-labextension` if possible.

**Comment by aidanheerdegen** [comment]
For testing purposes I have created an uploaded a conda extension

https://anaconda.org/coecms/dask-labextension

The conda recipe is here:

https://github.com/coecms/conda-skeletons/tree/master/dask-labextension

I added post link and unlink scripts to do the installation, but I'm not sure that is considered good practice now.

**Comment by jakirkham** [comment]
If you are comfortable submitting a PR to [staged-recipes]( https://github.com/conda-forge/staged-recipes ) @aidanheerdegen, would encourage you to do that.

As to best practices, I'd take a look at [this recipe]( https://github.com/conda-forge/jupyterlab-git-feedstock/tree/master/recipe ), which is also installing a JupyterLab extension and model it after that.

**Comment by ian-r-rose** [comment]
I agree it would be nice to have this in `conda-forge`, though I'm a bit lacking in time to get that set up. PRs to move this along would be most appreciated @aidanheerdegen

**Comment by aidanheerdegen** [comment]
Ok. I think I'll need to setup up a container to properly test installation. Does anyone have something appropriate already lying about?

**Comment by xhochy** [comment]
Setup the conda-forge package: https://github.com/conda-forge/dask_labextension-feedstock

**Comment by jakirkham** [comment]
Thanks @xhochy! Let's close this out. 😄

@aidanheerdegen, perhaps you could give that package a try and report feedback? 😉
