### ISSUE TITLE
What is standard dask-labextension behavior and usage

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-labextension#48]
Following discussion in #36 and especially comment https://github.com/dask/dask-labextension/pull/36#issuecomment-462329556.

First time I used dask-labextension was from a Pangeo binder, or maybe dask-examples binder. From there, nothing to do, windows (Task Stream and Progress) already opened, and they connect automatically when a LocalCluster is started, nice!

So I tried to deploy the extension on a Jupyterlab running on CNES HPC cluster in notebooks using dask-jobqueue. In order to make it work, I have to:

1. Start a cluster inside my notebook
1. Indicate scheduler URL in dask-labextension left panel
1. Open views on my lab environment

Is this the intended behavior? I'm specifically thinking of the second point, I guess that declaring a default layout of view in JLab must be somehow feasible, and it is not related to this extension. 

For the first point, I can see a _New_ button from the extension left panel, but it does nothing. Must it be configured somewhere? Readme says:

> Options for how to launch these clusters are set via the dask configuration system.

Maybe the docs should be a little more precise about this.

Anyway this is a great extension when using Dask, and on going work could make it still better, so thanks!

**Comment by andersy005** [comment]
As @ian-r-rose mentioned in https://github.com/dask/dask-labextension/pull/36#issuecomment-462427457:

> this functionality is intended to work with clusters managed by the extension (rather than ones launched in your notebook). It currently works with `LocalCluster`, and (possibly) `KubeCluster`

I am wondering if there's a plan for supporting  same functionality for `Cluster` objects such as `SLURMCluster` , `PBSCluster` created via `dask_jobqueue`? (Is this even feasible?)

**Comment by mrocklin** [comment]
> Start a cluster inside my notebook

This is being handled in https://github.com/dask/dask-labextension/pull/36

> Indicate scheduler URL in dask-labextension left panel 
> Open views on my lab environment

You can handle this by including a workspace json file in the user's environment. 
 This is what we do for examples.dask.org and also Pangeo I think.   https://github.com/dask/dask-examples/blob/master/binder/jupyterlab-workspace.json

> I am wondering if there's a plan for supporting same functionality for `Cluster` objects such as `SLURMCluster` , `PBSCluster` created via `dask_jobqueue`? (Is this even feasible?)

They would probably work today.  You can switch the default away from LocalCluster by changing the values in the labextension.yaml file.

https://github.com/dask/dask-labextension/blob/910f5fff9e4d50f79a8c42e0ecd14464bbc2a177/dask_labextension/labextension.yaml#L2-L6

However in order to make JupyterLab happy ideally we would be able to start and close a cluster asynchronously with 

```python
cluster = await SGECluster(...)
```

and 

```
await cluster.close()
```

I've been working on this within `KubeCluster` (currently available in the `dev` branch).  I suspect that it will be easier to accomplish within dask-jobqueue.

All of this could use better documentation.

**Comment by andersy005** [comment]
> They would probably work today. You can switch the default away from LocalCluster by changing the values in the labextension.yaml file.

@mrocklin, I can confirm that this works like a charm with `dask_jobqueue`

**Comment by ian-r-rose** [comment]
That's great @andersy005, thanks for checking! Would you be willing to document an example config file that works with `dask_jobqueue`? I'd like to start posting some of those in the README.md

**Comment by andersy005** [comment]
> Would you be willing to document an example config file that works with dask_jobqueue?

@ian-r-rose, definitely! I will submit a PR for this.

**Comment by mrocklin** [comment]
I'd also love to see this working in the NCAR JupyterHub :) 

It would be cool to see users manage large clusters with the sidebar .

**Comment by guillaumeeb** [comment]
Thanks for all the answers here. As per my original problem, there are some interrogations still open:
- Indicate scheduler URL in dask-labextension left panel: can the extension detect a new Cluster, without automatically starting it via #36?
- How must be configured the `New` button? Here is whta the readme says for reminder:
> Options for how to launch these clusters are set via the dask configuration system.

**Comment by ian-r-rose** [comment]
@andersy005 ping on this, do you happen to have an example configuration that works for `dask_jobqueue` that we can point to in the `README.md`?

**Comment by ian-r-rose** [comment]
@guillaumeeb Sorry for the slow cycle on this. To your specific questions
* No, there is currently no way to detect a cluster that has not been launched by the cluster manager itself. Though it doesn't need to be connected to via #36, you can explicitly write out the client connection code yourself, or inject it via the side panel.
* The configuration lies in the [labextension.yml](../blob/master/dask_labextension/labextension.yaml) file, or in a dask config file. That describes a module, a cluster class, and args+kwargs for creating the cluster. That is what you will want to define for your setup, which will then be used to create new clusters. Unfortunately, I don't have access to the breadth of clusters, nor the personal bandwidth to really run down all the different types of clusters that people are likely to want to use. So it would be really helpful if the community could try this out in a number of contexts, let me know what issues they find, and contribute back example configurations.

**Comment by andersy005** [comment]
@ian-r-rose, 

I am sorry for not getting back to you sooner. My `labextension.yml` contains:

```yaml
labextension:
   factory:
     module: 'dask_jobqueue'
     class: 'SLURMCluster'
     args: []
     kwargs: {}
   default:
    workers: null
    adapt: null
      # minimum: 0
      # maximum: 10
   initial: []
```

Since at NCAR we have two HPC systems that use different schedulers, in order to use the PBSCluster, I need to edit my `labextension.yml`

```yaml
labextension:
   factory:
     module: 'dask_jobqueue'
     class: 'PBSCluster'
     args: []
     kwargs: {}
   default:
    workers: null
    adapt: null
      # minimum: 0
      # maximum: 10
   initial: []
```

P.S.:

The last time I played with this, I made a screencast just in case people are interested to see this feature in action: https://youtu.be/Z8rcPaKHQk0

**Comment by ian-r-rose** [comment]
Thanks @andersy005! Would you mind if I include these and a link to your video in the README?

**Comment by andersy005** [comment]
> Would you mind if I include these and a link to your video in the README?

Sure thing! I was about to take some screenshots that can be added to the README but for some  reason things are broken despite my attempt at using the fix proposed in https://github.com/jupyterhub/jupyter-server-proxy/issues/109

```python
Traceback (most recent call last):
  File "/glade/work/abanihi/softwares/miniconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/glade/work/abanihi/softwares/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/glade/work/abanihi/softwares/miniconda3/lib/python3.6/site-packages/jupyter_server_proxy/websocket.py", line 87, in get
    return await self.http_get(*args, **kwargs)
  File "/glade/work/abanihi/softwares/miniconda3/lib/python3.6/site-packages/jupyter_server_proxy/handlers.py", line 247, in http_get
    return await self.proxy(port, proxy_path)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by ian-r-rose** [comment]
The most recent version of the python package (`dask_labextension`) bundles its own version of `jupyter-server-proxy` (at least for the time being). So it should be able to work without it. We are still having troubles with tornado 6 however, so I would keep things on tornado 5.1.1 if at all possible.

**Comment by ian-r-rose** [comment]
I've added some more documentation and examples to the README.md. Please let me know if it is still unclear, and we can reopen this and continue working on this.

Thanks for the feedback, all!
