### ISSUE TITLE
Switching to jupyter-server-proxy

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-labextension#49]
IIUC this is using `nbserverproxy` currently. As `jupyter-server-proxy` is the successor of `nbserverproxy` recently and made a 1.0 release, it would be good to switch to using `jupyter-server-proxy` instead.

**Comment by ian-r-rose** [comment]
Yes, switching to `jupyter-server-proxy` is a priority. I would say that is currently blocked by jupyterhub/jupyter-server-proxy#70

**Comment by ian-r-rose** [comment]
Fixed by #58.
