### ISSUE TITLE
Configuration broken for kwargs that have underscores

### ISSUE THREAD

**Issue by ian-r-rose** [dask/dask-labextension#56]
We currently ask users to configure clusters startup using `kwargs` in a config file. Unfortunately, dask's config normalizes underscores to hyphens, making the keys invalid python identifiers..

We can deal with it as a special case here, and replace hyphens with underscores before passing in the kwargs, but a nicer solution might be to have this fixed upstream.

xref https://github.com/dask/dask/pull/4422, https://github.com/dask/dask/issues/4366

**Comment by mrocklin** [comment]
cc @jcrist
