### ISSUE TITLE
dask labextension for HPC deployment

### ISSUE THREAD

**Issue by filippo82** [dask/dask-labextension#62]
Dear all,

I was able to follow (and modify) [this gide](http://pangeo.io/setup_guides/hpc.html) to set up Pangeo on the HPC system of my university (which uses LSF). I was able to deploy it and run it but not to use/connect the dask dashboard. I've installed dask_labextension but the buttons remain grey.

Any thoughts?

Thank you!

jupyter serverextension list says that everything is OK/enabled

**Comment by andersy005** [comment]
Hi @filippo82, 

Sorry for not getting back to you sooner... Is this still a relevant issue on your end?

**Comment by filippo82** [comment]
Dear @andersy005 
thanks for your reply. It is not relevant anymore.
Cheers.
