### ISSUE TITLE
Publishing git tags for 0.3.2 and 0.3.3

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-labextension#66]
Would be great to have the git tags for 0.3.2 and 0.3.3 published to GitHub (if possible).

**Comment by ian-r-rose** [comment]
Thanks for the reminder @jakirkham, I've pushed tags for the python 0.3.2 and 0.3.3 releases.

Unfortunately, I don't really have a good strategy for tags when there are two independently versioned packages in the repo, any thoughts?

**Comment by ian-r-rose** [comment]
Closing as the immediate issue is fixed.
