### ISSUE TITLE
Dask Server Error on Pangeo Binder instance

### ISSUE THREAD

**Issue by djhoese** [dask/dask-labextension#71]
As discussed on pangeo's gitter with @ian-r-rose, I'm playing around with updating a binderhub to use JupyterLab 1.0+. I used the Pangeo binder cookiecutter [here](https://github.com/pangeo-data/cookiecutter-pangeo-binder) as a starting point, but updated things to use newest JLab. The resulting repository is here: https://github.com/djhoese/tutorial-intro-python-satpy

When starting the service I get the error in the screenshot below:

![image](https://user-images.githubusercontent.com/1828519/61729903-e1896900-ad3d-11e9-9194-12d58cc6e0b1.png)

There is a good chance I'm missing one last thing to make this work. @TomAugspurger was also planning on looking at some of this today so there may be something on the Pangeo Binder instance that needs to be updated.

NOTE: I modified my jupyter lab workspace.json to remove the Dask dashboard panes. Not sure if that could cause issues.

**Comment by ian-r-rose** [comment]
Thanks @djhoese. If you open a terminal and enter `jupyter serverextension list`, what does it output? Does it indicate that `dask_labextension` is enabled?

**Comment by djhoese** [comment]
```
jovyan@jupyter-djhoese-2dtutoria-2dro-2dpython-2dsatpy-2dkzhpmvny:~$ jupyter serverextension list
config dir: /srv/conda/envs/notebook/etc/jupyter
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 1.0.2 OK
    nteract_on_jupyter  enabled 
    - Validating...
      nteract_on_jupyter 2.0.12 OK```

So doesn't look like it. I'd have to check the build logs (not sure if I can do that without rebuilding the image). postBuild has:

```
jupyter serverextension enable --py jupyter_server_proxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension

```

**Comment by ian-r-rose** [comment]
Ah, seems like you are missing the python package: I think it may be enough to include `dask-labextension` in your environment.yml: https://anaconda.org/conda-forge/dask-labextension

**Comment by djhoese** [comment]
Fixed it. Thanks.
