### ISSUE TITLE
Usage question: Existing client?

### ISSUE THREAD

**Issue by keflavich** [dask/dask-labextension#76]
If a client is started up within a notebook without specifying the tcp address, e.g.:
```
from dask.distributed import Client

client = Client(n_workers=8, threads_per_worker=8)
```
is there any way to connect the extension to it?   I don't see the client showing up in the left side extension window, and I don't know how to search for it.

Relatedly, what is the search bar for?  I'm not clear what I'm supposed to be searching for there, or if it's related to my question.

**Comment by ian-r-rose** [comment]
@keflavich Yes, if you print the client info, there should be a URL to the client dashboard. You can enter that URL in the search bar to access the dashboard. Clicking on the "Search" icon will attempt to do that automatically, but it's not especially robust.

An important caveat: depending on the network environment you are using, browser security policies may prevent the dashboards from connecting. In that case you may need to proxy the dashboard to the notebook server using `jupyter-server-proxy`. The `dask-examples` repo binder shows how that can be done.

**Comment by keflavich** [comment]
I think I see now.  The plugin is only operating locally on my machine, but I'm running jupyter lab ssh'd into another machine.  Port 8787 on that machine (or whatever port the client uses) is not forwarded to my machine).  Thanks, that answers my question.

Could you point me to the appropriate location in the `dask-examples` binder for using a proxy?  I see the `binder/` directory in that repo, but I'm not entirely clear what I'm supposed to be following.  Are you saying the instructions are in `https://github.com/dask/dask-examples`, or that I should read through `dask-examples` within a binder session?

**Comment by ian-r-rose** [comment]
Sorry, that was kind-of-rushed. If you are on your local machine and install `jupyter-server-proxy`, then you should also be able to put in `/proxy/8787` for the URL. In the context of `dask-examples`, it does some extra config for the binder to point at the right URL (modified for a hub environment): https://github.com/dask/dask-examples/blob/fe6eb9c40fee48f6aadd42da28d8bac9205a5026/.dask/config.yaml#L5-L6

**Comment by keflavich** [comment]
Thanks, that's much clearer and appears to work without any additional setup through my ssh port forwarding connection... which is remarkable.  I did install `jupyter-server-proxy` (on the remote machine), but I don't know if that was necessary.

Is there any way to get those proxy clusters to show up in the cluster list, or do I need to manually enter the cluster name in the search bar each time?

**Comment by ian-r-rose** [comment]
`jupyter-server-proxy` *should* be installed when installing `dask_labextension`, but people have run into issues there, so I was just trying to be explicit.

The clusters listing only knows about clusters that it creates itself, so if you do it out-of-band, there is no way to make them show up (at least not right now, we may tackle cluster discovery down the road).

**Comment by ian-r-rose** [comment]
Closing as answered, but let me know if you have any further questions @keflavich
