### ISSUE TITLE
Support for Dask-Yarn

### ISSUE THREAD

**Issue by bschreck** [dask/dask-labextension#77]
I'm not sure how hard it would be to allow Dask Yarn clusters. I tried it, and it fails because there is no `asynchronous` keyword in `YarnCluster.__init__`. I'm not sure if launching the cluster asynchronously would be necessary for this functionality.

**Comment by mrocklin** [comment]
I think that this would be resolved by
https://github.com/dask/dask-yarn/issues/95 , but I'm not sure.  It would
require some experimentation.  cc @jcrist

**Comment by ian-r-rose** [comment]
While the async story settles, you might want to try using [this](https://github.com/ian-r-rose/dask-labextension/tree/de-asyncify) branch, which removes the need for async cluster starting.

**Comment by bschreck** [comment]
@mrocklin That looks like it would probably resolve the issue.

In the meantime I think I can easily create my own branch. @ian-r-rose that doesn't quite work because there's no `cluster.scheduler` attribute for the YarnCluster.

**Comment by bschreck** [comment]
This seems to be working: https://github.com/bschreck/dask-labextension

**Comment by AlJohri** [comment]
hi, just wanted to check in on this issue- what is required to support Dask Yarn with the lab extension? I mostly just want to see the dask dashboard within jupyter lab, I can start the dask YarnCluster manually. Does this already work?

**Comment by mrocklin** [comment]
I recommend that people ask these questions at github.com/dask/dask-yarn .  The maintainer of Dask-Yarn sometimes doesn't check issues here.

**Comment by jcrist** [comment]
Apologies for the late response here. As of dask-yarn 0.8.0, asynchronous support works fine. Tested and verified it works with dask-labextension. This can be closed.
