### ISSUE TITLE
TheLittlestJupyterHub proxy 

### ISSUE THREAD

**Issue by jmunroe** [dask/dask-labextension#81]
I have the dask-labextension only partially working with a JupyterLab / TheLittlestJupyterHub environment. It appears to be a problem with how the proxies are configured.  An url like this works correctly:

https://cosima.munroelab.ca/user/jm0634/proxy/46793/status

but using

https://cosima.munroelab.ca/user/jm0634/dask/dashboard/9c845b0c-a6a2-4bd9-a12c-20228ae6040d/status

leaves the bokeh app connecting but none of the graphs appearing.  Any suggestions on how to debug this issue? Thanks.

**Comment by mrocklin** [comment]
@ian-r-rose @yuvipanda do you all have any thoughts on how these two proxy systems might differ in regards to websockets?

**Comment by ian-r-rose** [comment]
I have a few questions/things to check @jmunroe:
1. Are there any errors on the Javascript console or the Hub logs?
1. Does your setup work without JupyterHub (that is, a bare JupyterLab server)?
1. What versions of `dask_labextension` and `dask-labextension` are you using?
1. Might there be a rogue `nbserverproxy` installed somewhere?
1. Are you trying to go to those URLs directly or opening them as JupyterLab panes?

**Comment by jmunroe** [comment]
_1.   Are there any errors on the Javascript console or the Hub logs?_

On the Javascript console:
```
Source map error: request failed with status 404
Resource URL: https://cosima.munroelab.ca/user/jm0634/dask/dashboard/d11a3…7e/static/js/bokeh.min.js?v=547e7d2591695b654def5914bdd697fa
Source Map URL: bokeh.min.js.map

Firefox can’t establish a connection to the server at wss://cosima.munroelab.ca/user/jm0634/dask/dashboard/d11a309e-c790-41a5-b391-b47bd3ef957e/graph/ws?bokeh-protocol-version=1.0&bokeh-session-id=ysrQ2eTuLzdFK5y8zTWFdC7DwldL4z3aOTWpMkdYkYiV. bokeh.min.js:31:1944
[bokeh] Failed to connect to Bokeh server Error: Could not open websocket bokeh.min.js:31:6977
    pull_session https://cosima.munroelab.ca/user/jm0634/dask/dashboard/d11a309e-c790-41a5-b391-b47bd3ef957e/static/js/bokeh.min.js?v=547e7d2591695b654def5914bdd697fa:31
[bokeh] Lost websocket 0 connection, 1006 () bokeh.min.js:31:5288
Error: Could not open websocket bokeh.min.js:31:5846
[bokeh] Websocket connection 0 disconnected, will not attempt to reconnect bokeh.min.js:31:2868
```

I don't see anything in the Hub logs or the User server logs.

_2.   Does your setup work without JupyterHub (that is, a bare JupyterLab server)?_

Yes.

_3. What versions of dask_labextension and dask-labextension are you using?_

dask-labextension v1.0.1
dask_labextension 1.0.3

_4. Might there be a rogue nbserverproxy installed somewhere?_

probably not ??

_5. Are you trying to go to those URLs directly or opening them as JupyterLab panes?_
 
Tried both approaches with the same issue either way.

**Comment by jmunroe** [comment]
After uninstalling / reinstalling / rebuilding / restarting various components in the JupyterHub / JupyterLab / labextensions it looks like dask-labextension is now correctly working on my TLJH set up.  

Not really which particular combination of action go things working correctly, but the issue is now resolved.
