### ISSUE TITLE
Improve error message / installation process of dask-labextension

### ISSUE THREAD

**Issue by jmunroe** [dask/dask-labextension#83]
If only the lab extension is installed with

`jupyter labextensions install dask-labextension`

Then the error popup  'Failed to list clusters: might the server extension not be installed/enabled?' 

It is not entirely clear to a new user how to remedy issue.  The solution (as is in the docs) is to  install the python package `dask_labextension`

`pip install dask_labextension`  

For me, there was confusion between installing a python package, installing the labextension, the difference between `dask-labextension` and `dask_labextension`, and why `jupyter labextension install <..>` is a thing but `jupyter serverextension install <...>` is not a thing (and needs to be installed as python package.  

Could the error message be changed to be clearer on what exactly needs to be installed? (the python package `dask_labextension` rather than just saying the server extension is not available?)  Also, then running `jupyter labextension list` it reports back `dask-labextension v1.0.1  enabled  OK` even if the require server extension is not installed.

**Comment by jacobtomlinson** [comment]
I think this was fixed in #130.
