### ISSUE TITLE
Flicker

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#9]
@sccolbert noticed a flicker when resizing plots

![image](https://cloud.githubusercontent.com/assets/306380/19968748/452d190c-a1ac-11e6-97e5-6c553b304237.png)

"It's like the canvas is being resized (which clears it white automatically), but the plot is not being redrawn until the next animation frame

so you get one frame of white before seeing the new plot"

Also

```ts
setTimeout(function () {
    // wait until bokehjs is loaded and the plot is rendered and added to the index
    // there's almost definitely a more elegant way to do this
    that._plot_ref = Bokeh.index[that._bokeh_id].model;
}, 1000);
```

this sometimes generates an error because `Bokeh.index[that._bokeh_id]` is still undefined

**Comment by sccolbert** [comment]
gif version of flicker:
![browser](https://cloud.githubusercontent.com/assets/137289/19971109/19300c6a-a1ac-11e6-811a-081329d02777.gif)

**Comment by mrocklin** [comment]
Ah, thank you.  Didn't realize that the image didn't copy over.

**Comment by mrocklin** [comment]
This seems to be resolved in the new implemenation
