### ISSUE TITLE
Sidebar no longer detects dashboard

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-labextension#94]
Things in master work well if I create the dashboard from the sidebar, but it no longer seems to work well if I provide the address to an external dashboard

![image](https://user-images.githubusercontent.com/306380/65788618-155b8300-e121-11e9-8443-3b9d6737250d.png)

Note in this screenshot that the address of the current dashboard is provided to the sidebar, but the lab extension doesn't connect to it.

cc @ian-r-rose @thomcom

**Comment by ian-r-rose** [comment]
I can take a look at this this weekend some time.

**Comment by mrocklin** [comment]
Thanks Ian.  I appreciate it.
