### ISSUE TITLE
Add conda-forge install instructions to README

### ISSUE THREAD

**Issue by wtbarnes** [dask/dask-labextension#97]
dask-labextension is available on conda-forge, but the install instructions in the README only mention pip. There should also be a section with install instructions for for conda-forge

**Comment by mrocklin** [comment]
I'm not sure that installing from conda-forge will correctly install the
jupyterlab extension.  @ian-r-rose would know more though.

**Comment by ian-r-rose** [comment]
I think it's correct that the conda-forge package will not install the client-side extension, but neither will the pypi package. We can certainly include instructions for conda-forge.

Pull requests welcome @wtbarnes!
